# Generated by Django 5.2.7 on 2025-10-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ping_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('download_mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('upload_mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('isp_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
