# Generated by Django 5.2.7 on 2025-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedtestresult',
            name='isp_info',
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='download_latency_ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='jitter_ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='packet_loss_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='upload_latency_ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='download_mbps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='ping_ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='upload_mbps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
